#! /usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'pep8==1.7.0','console_scripts','pep8'
__requires__ = 'pep8==1.7.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('pep8==1.7.0', 'console_scripts', 'pep8')()
    )
